### PR TITLE
Support nullable fields.

### LINKED ISSUE #39: Support nullable fields
Facility doesn't currently distinguish missing fields from null fields when reading DTOs from JSON, and never writes null when writing DTOs to JSON. A nullable field would require clients and servers to support null fields and distinguish them from missing fields. They could be restricted to "normal" fields.

### PR DESCRIPTION
**Pull request by ejball**
Fixes #39.

### CODE REVIEW

**Comment by jzbrooks** [comment]
What would `[required]` mean on a nullable field (assuming nullable implies that a value will always be represented in the payload)? Should that combination be disallowed?

**Comment by ejball** [comment]
`[required]` would mean that it can't be missing from the payload, i.e. it must be set to a valid value or explicitly `null`.

**Comment by jzbrooks** [comment]
```
[required]
widget: nullable<Widget>; // must be specified - may be explicitly null

[required]
widget: Widget; // must be specified - may not be null

widget: Widget; // may not be specified - may be explicitly null (depending on serializer settings)
```

In that case, it seems like the fact that `nullable<T>` exists when every T is potentially nullable in a certain sense might be confusing.

I would expect explicit serialization of null values to be a parameter in facility configuration (like somewhere in `ServiceHttpHandlerSettings`), not in the API specification itself. Newtonsoft (and other serializers) have a setting for explicit encoding of null. Maybe that level of serializer configuration isn't possible in facility (or perhaps is not very easy).

Short of that, I'd expect an attribute to indicate particular exceptions to the serialization scheme over being codified in the type system. I'm curious why `[nullable]` didn't make the cut. It seems like you considered that from the linked issue.

**Comment by ejball** [comment]
I agree that it is confusing. I don't think I'll end up using it, but I don't want Facility to be passed over by clients that need it.

Before `nullable<T>`, `null` was not a supported concept in Facility. With `widget: Widget`, the object can be missing, or it can be specified, but it cannot not be "null", even though "null" might be how a particular language or serialization format supports the concept of "missing".

With `nullable<T>`, "null" becomes a supported value, which _must be distinguishable_ from "missing", so it really is a different type of data. `boolean` has three possible values (if you count "missing"); `nullable<boolean>` has four. Changing whether the JSON serializer writes `null` for missing properties would not accomplish this; in fact, the JSON serializer must not write `null` for missing properties for this to work.

In C#, that means introducing a new type (`ServiceField<T>`) that can distinguish missing from null and must only read/write a JSON `null` as approprate (no easy task). JavaScript and TypeScript already support the distinction via `undefined` vs. `null`. It may be that some languages choose not to support it at all...

Thanks for the feedback! I'm happy to continue to address questions or concerns.

**Pull request merged**
